### ISSUE TITLE
CLAP format build targets?

### ISSUE THREAD

**Issue by mxmilkiib** [VASTDynamics/Vaporizer2#3] opened 2023-09-28 01:41 UTC
Hi! I was wondering if LV2 (and CLAP) plugin format builds might be possible? Thanks!

**Comment by steveb** [comment] 2023-09-30 01:26
Another request for LV2 :)

**Comment by dromer** [comment] 2023-09-30 15:56
The project is still using JUCE 6.1.6 - so it would first need to be updated to 7.x

No idea if there are customizations done to the JUCE code, since the entire codebase is vendored into this repo.

**Comment by KottV** [comment] 2023-10-05 23:12
@VASTDynamics
Hi, I see https://github.com/VASTDynamics/Vaporizer2/commit/a107c0ae4d379b453a6a21bf53222b6f40a832f3

What LV2 URI do you plan to keep? By default it will be `www.vast-dynamics.com/plugins/VASTvaporizer2`, maybe you'll decide to change it, while LV2 version is not published.

**Comment by dromer** [comment] 2023-10-06 02:09
@KottV wow, amazing!

Would it make sense to turn JUCE into a submodule? or are there certain patches made to work with the project?

**Comment by VASTDynamics** [comment] 2023-10-06 11:42
> @VASTDynamics Hi, I see [a107c0a](https://github.com/VASTDynamics/Vaporizer2/commit/a107c0ae4d379b453a6a21bf53222b6f40a832f3)
> 
> What LV2 URI do you plan to keep? By default it will be `www.vast-dynamics.com/plugins/VASTvaporizer2`, maybe you'll decide to change it, while LV2 version is not published.

I would go with the default www.vast-dynamics.com/plugins/VASTvaporizer2. This is what I have at the moment in Projucer. Or would you recommend something else?

**Comment by VASTDynamics** [comment] 2023-10-06 11:45
> @KottV wow, amazing!
> 
> Would it make sense to turn JUCE into a submodule? or are there certain patches made to work with the project?

Hm, yes, that might be not clean. There are absolutely no changes to JUCE modules. Yet I found it always handy to have the very same JUCE version in the project that the code is tested with. E.g. in the beta branch I have updgraded to JUCE 7 which required some adaptations.

**Comment by dromer** [comment] 2023-10-06 11:52
> Yet I found it always handy to have the very same JUCE version in the project that the code is tested with.
I don't really understand what you mean by this. Using submodules you can pin to a specific commit/branch/repo and it keeps your project relatively clean.

**Comment by VASTDynamics** [comment] 2023-10-06 12:46
> > Yet I found it always handy to have the very same JUCE version in the project that the code is tested with.
> 
> I don't really understand what you mean by this. Using submodules you can pin to a specific commit/branch/repo and it keeps your project relatively clean.

Yes, You are right. In the beta branch I have now moved JUCE and muFFT to submodules. Thanks for the hint.

**Comment by KottV** [comment] 2023-10-07 03:48
> I would go with the default [www.vast-dynamics.com/plugins/VASTvaporizer2](http://www.vast-dynamics.com/plugins/VASTvaporizer2). This is what I have at the moment in Projucer. Or would you recommend something else?

good, I've asked just to be sure

**Comment by VASTDynamics** [comment] 2023-10-09 19:02
Merged in beta

**Comment by KottV** [comment] 2023-10-09 20:08
for a CLAP there should be a  separate issue, as that feature may be available after porting to CMake only

**Comment by mxmilkiib** [comment] 2023-10-12 18:08
The description could do with a small update :) Thanks again!

**Comment by VASTDynamics** [comment] 2023-10-12 18:25
Changed the issue to focus on CLAP and reopened it.

**Comment by VASTDynamics** [comment] 2023-11-08 14:56
LV2 will be part of the next release. Still looking into CLAP.

**Comment by atsushieno** [comment] 2023-12-07 12:10
Yes, I confirmed it loads on Reaper 7.0.5. I confirmed it only on Mac for this one though.

<img width="1335" alt="image" src="https://github.com/VASTDynamics/Vaporizer2/assets/53929/0d58ac57-f3d5-4c15-a729-f233ce9f9b2d">

**Comment by VASTDynamics** [comment] 2023-12-07 13:09
Oh, it says "undefined". I will add the CLAP type in coding. 
Can you tell me which branches of clap, clap-helpers and clap-juce-extensions you have used?

**Comment by VASTDynamics** [comment] 2023-12-23 17:55
Vaporizer2 3.4.3 as CLAP on Windows in Reaper
![image](https://github.com/VASTDynamics/Vaporizer2/assets/35850267/138adee1-1038-4b0b-b6c0-ab58b109391c)

**Comment by VASTDynamics** [comment] 2023-12-25 17:47
Please check:
https://github.com/VASTDynamics/Vaporizer2/releases/tag/v3.4.5

**Closed** 2023-12-28 09:20 UTC
Labels: enhancement, in next release

**Comment by RustoMCSpit** [comment] 2024-04-23 10:02
where do i install the linux clap version?
